# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui файлы/Шаблон.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.action.setText(_translate("MainWindow", "Создать"))
        self.action_2.setText(_translate("MainWindow", "Удалить"))

#========================================================
from PyQt5.QtWidgets import QMainWindow, QApplication
import sys


class Window(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(Window, self).__init__()
        self.setupUi(self)
        self.setWindowTitle("Название окно")

        self.toolBar = QtWidgets.QToolBar(self) # Создаем новую панель инструментов и присваиваем ее self.toolBar

        self.toolBar.setObjectName("toolBar") # Устанавливаем имя объекта для панели инструментов (может быть полезно для стайлинга или отладки)

        self.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar) # Добавляем панель инструментов в главное окно в верхнюю область

        self.plus = QtWidgets.QAction(QtGui.QIcon('plus.png'), '+' , self)
        self.minus = QtWidgets.QAction(QtGui.QIcon('minus.png'), '+' , self) # Создаем действие с иконкой и присваиваем в self.minus
        self.toolBar.addAction(self.plus) # Добавляем действие на панель инструментов
        self.toolBar.addAction(self.minus)

        self.toolBar.setMovable(False) # Делает панель инструментов неподвижной (нельзя перетаскивать)
        self.toolBar.addSeparator() # Добавляет разделитель на панели инструментов для визуального группирования

        # Связываем сигнал 'triggered' действия '+' с методом увеличения масштаба
        self.plus.triggered.connect(self.upScale)
        self.minus.triggered.connect(self.downScale)


    def upScale(self): # Увеличиваем ширину и высоту на 10 пикселей
        rect = self.rect().getRect() # Получаем текущий размер и координаты окна
        self.resize(rect[2] + 10, rect[3] + 10) # Меняем размер окна на новый
    def downScale(self): # Уменьшаем ширину и высоту на 10 пикселей
        rect = self.rect().getRect()
        self.resize(rect[2] - 10, rect[3] - 10)

def application():
    app = QApplication(sys.argv)
    window = Window()
    window.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    application()
